# Generated by Django 6.1.2 on 2026-10-08 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('temp_max', models.FloatField()),
                ('temp_min', models.FloatField()),
                ('condition', models.CharField(max_length=100)),
                ('rain_probability', models.IntegerField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather', to='destinations.destination')),
            ],
            options={
                'ordering': ['forecast_date'],
                'unique_together': {('destination', 'forecast_date')},
            },
        ),
    ]
